fix patch file for handbrake

diff --git a/media-video/handbrake/files/handbrake-9999-dont-search-for-python.patch b/media-video/handbrake/files/handbrake-9999-dont-search-for-python.patch
--- a/media-video/handbrake/files/handbrake-9999-dont-search-for-python.patch
+++ b/media-video/handbrake/files/handbrake-9999-dont-search-for-python.patch
@@ -1,26 +1,22 @@
 --- a/configure
 +++ b/configure
-@@ -14,20 +14,8 @@ inpath()
+@@ -12,13 +12,11 @@
+     return 1
  }
- 
- if ( inpath bash ); then
--    pp=""
--    for p in python3 python3.8 python3.7 python3.6 python3.5 python3.4 python3.3 python3.2 python3.1 python2 python2.7 python
--    do
--        if ( inpath $p ); then
--            pp="$p"
--            break
--        fi
--    done
--    if [ "$pp" != "" ]; then
--        exec $pp `dirname $0`/make/configure.py "$@"
+
+-for p in python3 python3.11 python3.10 python3.9 python3.8 python3.7 python3.6 python
+-do
+-    if ( inpath $p ); then
+-        exec $p `dirname $0`/make/configure.py "$@"
 -        exit 0
--    else
--        echo "ERROR: no suitable version of python found."
 -    fi
+-done
++if ( inpath bash ); then
 +    exec python `dirname $0`/make/configure.py "$@"
 +    exit 0
- else
-     echo "ERROR: bash shell not found."
- fi
++else
++    echo "ERROR: bash shell not found."
++fi
 
+-echo "ERROR: no suitable version of python found."
+ exit 1
